on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Publish package
      id: publish_package
      uses: coactions/setup-xvfb@v1
      with:
        run: mvn -B package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        # MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    - name: Release Upload Assets
      uses: jaywcjlove/github-action-upload-assets@main
      if: steps.publish_package.outputs.successful == 'true'
      with:
        asset-path: '["./mydoggy/mydoggy-api/target/*.jar", "./mydoggy/mydoggy-examples/target/*.jar", "./mydoggy/mydoggy-plaf/target/*.jar", "./mydoggy/mydoggy-res/target/*.jar", "./mydoggy/mydoggy-site-skin/target/*.jar"]'
